theme: jekyll-theme-minimal

collections:
  classes:
    output: true
	permalink: /awesome/:path/:title.:output_ext
  modules:
    output: true
	permalink: /awesome/:path/:title.:output_ext
  interfaces:
    output: true
	permalink: /awesome/:path/:title.:output_ext
