theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
