theme: jekyll-theme-minimal

collections:
  classes:
    permalink: /:collection/:path/
    output: true
  modules:
    permalink: /:collection/:path/
    output: true
  interfaces:
    permalink: /:collection/:path/
    output: true
